---

x-common-settings:
  &common-settings
  image: freqtradeorg/freqtrade:stable
  build:
    context: ..
    dockerfile: "../docker/Dockerfile.custom"
  restart: unless-stopped
  volumes:
    - "../user_data:/freqtrade/user_data"
    - "../user_data/data:/freqtrade/user_data/data"
    - "../configs:/freqtrade/configs"
    - "../consumer_setup:/freqtrade/consumer_setup"
    - "../${STRATEGY:-NostalgiaForInfinityX6}.py:/freqtrade/${STRATEGY:-NostalgiaForInfinityX6}.py"
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "http://localhost:${API_SERVER__LISTEN_PORT:-8080}"]
  #   interval: 1m30s
  #   timeout: 10s
  #   retries: 3
  #   start_period: 40s
  #   start_interval: 5s

services:

  freqtrade-consumer:
    <<: *common-settings
    container_name: ${CONSUMER_BOT_NAME:-Example_Test_Account}_${EXCHANGE_NAME:-binance}_${TRADING_MODE:-spot}-${STRATEGY:-NostalgiaForInfinityX6}
    ports:
      - "${CONSUMER_LISTEN_PORT:-8989}:${CONSUMER_LISTEN_PORT:-8989}"
    env_file:
      - path: env/common-all.env
        required: false # default true
      - path: env/consumer.env
        required: false # default true
      - path: env/producer_list_${NUM_OF_BOTS:-2}bots.env
        required: false # default true
      - path: env/pairlists/pairlist-${PAIRLIST_MODE:-volume}-${EXCHANGE_NAME:-binance}-${PAIRLIST_CURRENCY:-${STAKE_CURRENCY:-USDT}}.env
        required: false # default true
    # depends_on:
    #   - freqtrade-producer1
    command: >
      trade
      --db-url sqlite:////freqtrade/user_data/${CONSUMER_BOT_NAME:-Example_Test_Account}_${EXCHANGE_NAME:-binance}_${TRADING_MODE:-spot}-tradesv3.sqlite
      --log-file user_data/logs/${CONSUMER_BOT_NAME:-Example_Test_Account}-${EXCHANGE_NAME:-binance}-${STRATEGY:-NostalgiaForInfinityX6}-${TRADING_MODE:-spot}.log
      --config user_data/config.json
      --config configs/blacklist-${EXCHANGE_NAME}.json
      --config consumer_setup/configs/producer_list.json
      --strategy-path .

  freqtrade-producer1:
    <<: *common-settings
    container_name: ${PRODUCER1_BOT_NAME:-Producer_1}_${EXCHANGE_NAME:-binance}_${TRADING_MODE:-spot}-${STRATEGY:-NostalgiaForInfinityX6}
    ports:
      - "${PRODUCER1_LISTEN_PORT:-8981}:${PRODUCER1_LISTEN_PORT:-8981}"
    env_file:
      - path: env/common-all.env
        required: false # default true
      - path: env/common-producer.env
        required: false # default true
      - path: env/producer1.env
        required: false # default true
      - path: env/pairlists/producers/pairlist-${PAIRLIST_MODE:-volume}-${EXCHANGE_NAME:-binance}-${PAIRLIST_CURRENCY:-${STAKE_CURRENCY:-USDT}}-producer.env
        required: false # default true
    command: >
      trade
      --db-url sqlite:////freqtrade/user_data/${PRODUCER1_BOT_NAME:-Producer_1}_${EXCHANGE_NAME:-binance}_${TRADING_MODE:-spot}-tradesv3.sqlite
      --log-file user_data/logs/${PRODUCER1_BOT_NAME:-Producer_1}-${EXCHANGE_NAME:-binance}-${STRATEGY:-NostalgiaForInfinityX6}-${TRADING_MODE:-spot}.log
      --config consumer_setup/configs/config_producer1.json
      --config configs/blacklist-${EXCHANGE_NAME}.json
      --strategy-path .

